// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flkcsndnrqsxzopzfcsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsa2NzbmRucnFzeHpvcHpmY3NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzE3NTIsImV4cCI6MjA3MDUwNzc1Mn0._xCse7lXVfB1atDBUiTJdfe_OE9dRqlff0nHj8qbzP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});